//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationGaragistesDAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimulationGaragistesEntities : DbContext
    {
        public SimulationGaragistesEntities()
            : base("name=SimulationGaragistesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Garagistes> Garagistes { get; set; }
        public DbSet<Franchises> Franchises { get; set; }
        public DbSet<Marques> Marques { get; set; }
        public DbSet<Modeles> Modeles { get; set; }
        public DbSet<Révisions> Révisions { get; set; }
        public DbSet<Revisions_Garagistes> Revisions_Garagistes { get; set; }
        public DbSet<Vacances> Vacances { get; set; }
    }
}
