//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationGaragistesDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Révisions
    {
        public Révisions()
        {
            this.Revisions_Garagistes = new HashSet<Revisions_Garagistes>();
        }
    
        public int id { get; set; }
        public string label { get; set; }
        public int defaultTime { get; set; }
        public Nullable<int> modele_id { get; set; }
        public Nullable<int> km { get; set; }
    
        public virtual Modeles Modeles { get; set; }
        public virtual ICollection<Revisions_Garagistes> Revisions_Garagistes { get; set; }
    }
}
