//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationGaragistesDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulations
    {
        public Simulations()
        {
            this.Statistiques = new HashSet<Statistiques>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<int> duree { get; set; }
        public Nullable<System.DateTime> debut { get; set; }
    
        public virtual ICollection<Statistiques> Statistiques { get; set; }
    }
}
