//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationGaragistesDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistiques
    {
        public int id { get; set; }
        public int revision_id { get; set; }
        public int garagiste_id { get; set; }
        public int simulation_id { get; set; }
        public Nullable<int> duree { get; set; }
        public string voiture { get; set; }
        public string revision { get; set; }
        public string garagiste { get; set; }
        public int modele_id { get; set; }
        public int km { get; set; }
        public int nbvacances { get; set; }
    
        public virtual Simulations Simulations { get; set; }
    }
}
