//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationGaragistesDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacances
    {
        public Vacances()
        {
            this.debut = DateTime.Now;
            this.fin = DateTime.Now.AddDays(1);
        }
        public int id { get; set; }
        public System.DateTime debut { get; set; }
        public System.DateTime fin { get; set; }
        public int garagiste_id { get; set; }
    
        public virtual Garagistes Garagistes { get; set; }
    }
}
